const MESSAGE_TYPE_DATA = 1;
const MESSAGE_TYPE_HEADERS = 2;
const MESSAGE_TYPE_REQUEST = 3;
const MESSAGE_TYPE_IDENTIFY = 4;
const MESSAGE_TYPE_EOF = 5;
const MESSAGE_TYPE_RESPONSE = 6;

module.exports = {
  MESSAGE_TYPE_DATA,
  MESSAGE_TYPE_HEADERS,
  MESSAGE_TYPE_REQUEST,
  MESSAGE_TYPE_IDENTIFY,
  MESSAGE_TYPE_EOF,
  MESSAGE_TYPE_RESPONSE,
}
